### ISSUE TITLE
New style of middleware 

### ISSUE THREAD

**Issue by Pajinek** [underyx/aiohttp-sentry#15]
New style of middleware https://github.com/aio-libs/aiohttp/pull/2252

I received following warning: 

```
/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py:165: DeprecationWarning:
old-style middleware "<aiohttp_sentry.SentryMiddleware object at 0x7f723aadf2b0>" deprecated, see #2252
```

**Comment by Arrekin** [comment]
+1, Had to manually suppress this warning in pytest

**Comment by maroshmka** [comment]
I guess https://github.com/underyx/aiohttp-sentry/pull/16 should do it. 

Im not sure about backward compatibility - when was `web.middleware` added and what changes was done now - if only definition or functionality. Nevertheless, I tested it with aiohttp==3.1.0 and it worked.

**Comment by underyx** [comment]
Yep, fixed by https://github.com/underyx/aiohttp-sentry/pull/16, thank you all!
